* Introduction

The follwing is my DOOM config in literate form for not only better navigation, but a better learning experience.

I spent a while trying to recreate what doom gives and all I ended up with was a worse version of doom. So this is the end game.

** Navigation

The main navigation of this file is through the custom minor mode =config-mode= which is setup later in the =Core -> Conifg= section of the document. Essentially, =config-mode= will setup a sidebar with the heading levels where you can navigate and filter out only the content from that heading.

To open up the config file with =config-mode= enabled, use the shortcut =<leader>C=. Once editing the document, there are a few options for navigating while using =config-mode=:

1. Selecting the header using the sidebar

   Switch over to the sidebar buffer and select (=RETURN=) the desired heading

2. Using =config-mode= shortcuts

   * =C-c C-n= or =C-c C-p= for next and previous headers
   * =C-c C-S-n= or =C-c C-S-p= for next and previous /section/

3. Toggle the sidebar

   You can also toggle the sidebar at any point to edit the document as a regular org file using =C-`=

Additionally, if at any point you add or remove a heading you can use the binding =U= while within the sidebar buffer to update the list.

* Core

** Profiler

To gauge the performance of the config, we use a custom function throughout the document to measure how much time each section takes, and profile which ones need attention if startup time spikes.

Each major header (Core, UI, Editor) will invoke the timer at the top level and also contain a 'Benchmark' section, where we report the time to the messages buffer.

#+begin_src emacs-lisp
(defvar my/init-start-time (current-time) "Time when init.el was started")
(defvar my/section-start-time (current-time) "Time when section was started")
(defun my/report-time (section)
  (message "%-36s %.2fs"
           (concat section " " "section time: ")
           (float-time (time-subtract (current-time) my/section-start-time))))
(message "---------------------------------------------------------------")

(setq my/section-start-time (current-time))

#+end_src

** Secrets

We'll need a place to store personal information such as api keys or email addresses. For this I use a file stored in the doom config directory called =secrets.el=. Since this information will vary from user to user, you'll need to create this yourself.

#+begin_src emacs-lisp
(load! "secrets")

#+end_src

** Nano Packages

There are a few UI based nano packages that need to be installed first. We'll declare them through the [[file:packages.el][packages.el]] file

#+begin_src emacs-lisp :tangle "packages.el"
;; these first 2 are necessary dependencies ;;

(package! nano-base-colors    ;; describes the base colors of nano theme
  :recipe (:host github
           :repo "rougier/nano-emacs"
           :files ("nano-base-colors.el")))

(package! nano-faces          ;; defines faces for nano theme
  :recipe (:host github
           :repo "rougier/nano-emacs"
           :files ("nano-faces.el")))

(package! nano-theme
  :recipe (:host github
           :repo "rougier/nano-theme"))

(package! nano-modeline
  :recipe (:host github
           :repo "rougier/nano-modeline"
           :branch "rewrite"))

(package! svg-lib
  :recipe (:host github :repo "rougier/svg-lib"))
(package! svg-tag-mode
  :recipe (:host github :repo "rougier/svg-tag-mode"))

#+end_src

** Config

The main reason I chose a literate config for this was to mitigate the pain of configuring a large single file... by using a large single file.

However, by taking advanatage of the imenu, and some packages from [[github:rougier][rougier]], we're able to create a minor mode to ease the process of editing a literate config.

Most of this is copy/pasted from [[github:rougier/dotemacs][this section]] of his literate config

*** Sidebar

First, this will require the [[github:bmag/imenu-list][imenu-list]] plugin. We'll install it from within the [[file:packages.el][packages.el]] file.

#+begin_src emacs-lisp :tangle "packages.el"
(package! imenu-list)

#+end_src

Then, we need to disable the popup rules for this sidebar window

#+begin_src emacs-lisp
(set-popup-rule! "^\\*Ilist\\*$" :side 'left :size 36 :select t :quit nil :ttl nil)

#+end_src

And create a custom nano-modeline format rule for the sidebar. I basically just copy and pasted the default format and hardcoded the file name.

#+begin_src emacs-lisp
(defcustom nano-modeline-format-config
  (cons '(nano-modeline-element-buffer-status
          nano-modeline-element-space
          "config.el"
          nano-modeline-element-space
          "(outline)")
        '(nano-modeline-element-window-status
          nano-modeline-element-space))
  "Config mode sidebar format"
  :type 'nano-modeline-type
  :group 'nano-modeline-modes)

#+end_src

#+begin_src emacs-lisp
;;; ========================== START CONFIG MODE ==========================

(require 'imenu)
(require 'imenu-list)

(defun my/org-tree-to-indirect-buffer ()
  "Create indirect buffer for current subtree and display it
in the main window instead of creating a new split."

  (let* ((origin (selected-window))
         (target (get-mru-window nil nil t)))
    (org-tree-to-indirect-buffer)
    (let ((ibuf (current-buffer)))
      ;; kill the window Org just created
      (delete-window)
      ;; show indirect buffer where the main buffer was
      (select-window target)
      (switch-to-buffer ibuf))
    (org-show-block-all)
    (setq-local my/org-blocks-hidden nil)))

(defun my/org-sidebar ()
  "Open an imenu list on the left that allow navigation."

  (interactive)
  (setq imenu-list-after-jump-hook #'my/org-tree-to-indirect-buffer
        imenu-list-position 'left
        imenu-list-size 36
        imenu-list-focus-after-activation t)

  (let ((heading (substring-no-properties (or (org-get-heading t t t t) ""))))
    (when (buffer-base-buffer)
      (switch-to-buffer (buffer-base-buffer)))
    (imenu-list-minor-mode)
    (imenu-list-stop-timer)
    (hl-line-mode)
    ;; (face-remap-add-relative 'hl-line :inherit 'nano-subtle)
    (nano-modeline nano-modeline-format-config 'header)
    (display-line-numbers-mode 0)
    ;; (setq header-line-format
    ;;       '(:eval
    ;;         (nano-modeline-render nil
    ;;                               (buffer-name imenu-list--displayed-buffer)
    ;;                               "(outline)"
    ;;                               "")))
    (setq-local cursor-type nil)
    (when (> (length heading) 0)
      (goto-char (point-min))
      (search-forward heading)
      (imenu-list-display-dwim))))

#+end_src

This toggles the org sidebar

#+begin_src emacs-lisp
(defun my/org-sidebar-toggle ()
  "Toggle the org-sidebar"

  (interactive)
  (if (get-buffer-window "*Ilist*")
      (progn
        (quit-window nil (get-buffer-window "*Ilist*"))
        (switch-to-buffer (buffer-base-buffer)))
    (my/org-sidebar)))

#+end_src

Make sure tangle is applied to the base buffer and not the subtree.

#+begin_src emacs-lisp
(defun my/org-babel-tangle ()
  "Write code blocks to source-specific files from the base buffer."

  (interactive)
  (with-current-buffer (or (buffer-base-buffer)
                           (current-buffer))
    (org-babel-tangle)))

#+end_src

Toggle code block folding; starting folded

#+begin_src emacs-lisp
(defvar my/org-blocks-hidden nil)

(defun my/org-toggle-blocks ()
  "Toggle code blocks folding."

  (interactive)
  (if my/org-blocks-hidden
      (org-show-block-all)
    (org-hide-block-all))
  (setq-local my/org-blocks-hidden (not my/org-blocks-hidden)))

(add-hook 'config-mode-hook #'my/org-toggle-blocks)

#+end_src

#+begin_src emacs-lisp
(defvar my/imenu-list-folding-status t
  "Folding status of the imenu-list")

(defun my/imenu-list-toggle-folding ()
  "Toggle top level nodes of the imenu-list buffer"

  (interactive)
  (with-current-buffer "*Ilist*"
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward "^\\+ " nil t)
        (if my/imenu-list-folding-status
            (hs-hide-block)
          (hs-show-block)))
      (setq my/imenu-list-folding-status (not my/imenu-list-folding-status)))))

;; (bind-key "S-<tab>" #'my/imenu-list-toggle-folding imenu-list-major-mode-map)
(bind-key "C-<tab>" #'my/imenu-list-toggle-folding imenu-list-major-mode-map)

#+end_src

Some information for when a top node is closed

#+begin_src emacs-lisp
(defun my/display-code-line-counts (ov)
  (when (eq 'code (overlay-get ov 'hs))
    (overlay-put ov 'display
                 (propertize
                  (format " [%d sections] … "
                          (- (count-lines (overlay-start ov)
                                       (overlay-end ov)) 1))
                  'face 'nano-faded))))

(setq hs-set-up-overlay #'my/display-code-line-counts)

#+end_src

#+begin_src emacs-lisp
(defun my/imenu-list-display-dwim ()
  "Display or toggle the entry at `point'."
  (interactive)
  (save-selected-window
    (save-excursion
      (my/imenu-list-ret-dwim))))

(defun my/imenu-list-ret-dwim ()
  "Jump to or toggle the entry at `point'."
  (interactive)
  (save-excursion
    (let ((entry (imenu-list--find-entry)))
      (when (imenu--subalist-p entry)
        (setq entry (cons
                     (car entry)
                     (get-text-property 0 'marker (car entry)))))
      (imenu-list--goto-entry entry))))

(bind-key "<SPC>" #'my/imenu-list-display-dwim imenu-list-major-mode-map)
(bind-key "<return>" #'my/imenu-list-ret-dwim imenu-list-major-mode-map)

#+end_src

*** Filter :BINDING:

This provide the my/org-imenu-filter that allows us to filter thw sidebar entries using the specified expression (e.g. “+HOOK +DEFER”).

#+begin_src emacs-lisp
(bind-key "C-c f" #'my/org-imenu-filter)
(bind-key "f" #'my/org-imenu-filter imenu-list-major-mode-map)
(bind-key "U" #'imenu-list-refresh imenu-list-major-mode-map)

#+end_src

3 levels for org-imenu

#+begin_src emacs-lisp
(setq org-imenu-depth 3)

#+end_src

#+BEGIN_QUOTE
   If you end up changing the line-height (in the =UI -> Font= section)
    you'll need to change the =:height= parameter in the =svg-tags= call of
    the =my/org-imenu-filter-tree= to =1= for the tags to not look distorted
#+END_QUOTE

#+begin_src emacs-lisp
;; (require 'org)
;; (require 'svg-tag-mode)

(defvar my/org-imenu-filter-history
  '("BINDING" "HOOK" "ADVICE" "FACE" "MODE" "DEFER" "TODO"
    "PERSONAL" "INACTIVE" "BUGFIX" "OTHER" "TIMER" "OS")
  "Filter history list.")

;; (defvar my/org-imenu-filter-function
;;   (cdr (org-make-tags-matcher "*"))
;;   "Filter function to decide if a headline is kept")
(defvar my/org-imenu-filter-function nil
  "Filter function to decide if a headline is kept")
;; Initialize it only when first needed
(defun my/org-imenu-filter-function-get ()
  (unless my/org-imenu-filter-function
    (setq my/org-imenu-filter-function
          (cdr (org-make-tags-matcher "*"))))
  my/org-imenu-filter-function)

(defun my/org-imenu-filter ()
  "Define and apply a new filter"

  (interactive)
  (let* ((match (completing-read-multiple
                 "FILTER: "
                 my/org-imenu-filter-history
                 nil nil nil
                 'my/org-imenu-filter-history))
         (match (mapconcat #'identity match " ")))
    (when (string= "" match)
      (setq match "*"))
    (setq my/org-imenu-filter-function
          (cdr (org-make-tags-matcher match)))
    (imenu-list-refresh)))


(defun my/org-imenu-filter-tree (&optional bound parent-match)
  "Build a imenu list using current filter function"

  (let* ((headlines '()))
    (save-excursion
      (org-with-wide-buffer
       (unless bound
         (setq bound (point-max))
         (goto-char (point-min)))
       (while (re-search-forward org-heading-regexp bound t)
         (let* ((element (org-element-at-point))
                (begin (org-element-property :begin element))
                (end (org-element-property :end element))
                (marker (copy-marker begin))
                (level (org-element-property :level element))
                (tags (save-excursion
                         (goto-char begin)
                          (org-get-tags)))
                (match (save-excursion
                         (goto-char begin)
                         (funcall (my/org-imenu-filter-function-get)
                                  nil (org-get-tags) level)))

                (title (org-element-property :raw-value element))
                (title (org-link-display-format
                        (substring-no-properties title)))
                (title (propertize title 'org-imenu-marker marker
                                         'org-imenu t))
                (title (if (member "INACTIVE" tags)
                           (propertize title 'face 'nano-faded)
                         title))
                (svg-tags (mapconcat #'(lambda (tag)
                                     (propertize tag 'display (svg-tag-make tag
                                                                            :face 'nano-faded
                                                                            :height 0.75)))
                                 tags " "))
                (title (if tags (format "%s %s" title svg-tags) title))
                (title (propertize title 'marker marker))
                (children (my/org-imenu-filter-tree end match)))
           (goto-char end)

           (cond ((> level org-imenu-depth)
                  nil)
                 ((> (length children) 0)
                  (add-to-list 'headlines (append (list title) children) t))
                 ((or match parent-match)
                  (add-to-list 'headlines (cons title marker) t)))))))
    headlines))

(advice-add #'org-imenu-get-tree :override #'my/org-imenu-filter-tree)

#+end_src

*** Config mode :BINDING:

This section defines the =my/config-mode= to ease navigating and editing the configuration file.

Navigation commands using the ilist menu.

#+begin_src emacs-lisp
(defun my/config-mode-prev-header ()
  "Move to previous header"

  (interactive)
  (with-current-buffer "*Ilist*"
    (search-backward-regexp "^  ")
    (imenu-list-display-dwim)))

(defun my/config-mode-next-header ()
  "Move to next header"

  (interactive)
  (with-current-buffer "*Ilist*"
    (forward-line)
    (search-forward-regexp "^  ")
    (imenu-list-display-dwim)))

(defun my/config-mode-prev-section ()
  "Move to previous section"

  (interactive)
  (with-current-buffer "*Ilist*"
    (search-backward-regexp "\\+ " nil nil 2)
    (forward-line)
    (imenu-list-display-dwim)))

(defun my/config-mode-next-section ()
  "Move to next section"

  (interactive)
  (with-current-buffer "*Ilist*"
    (previous-line)
    (search-forward-regexp "\\+ ")
    (forward-line)
    (imenu-list-display-dwim)))

#+end_src

The minor mode for configuration

#+begin_src emacs-lisp
(define-minor-mode my/config-mode
  "Configuration mode"

  :init-value nil
  :global nil
  :keymap (let* ((map (make-sparse-keymap)))
            (bind-key "C-c C-p"   #'my/config-mode-prev-header map)
            (bind-key "C-c C-n"   #'my/config-mode-next-header map)
            (bind-key "C-c C-S-p" #'my/config-mode-prev-section map)
            (bind-key "C-c C-S-n" #'my/config-mode-next-section map)
            (bind-key "C-`"       #'my/org-sidebar-toggle map)
            map)

  (require 'org)
  (require 'svg-tag-mode)
  (if my/config-mode
      (my/org-sidebar)))

#+end_src

And lastly, define a shortcut function to open this file with config mode enabled. We will also bind this to a key for easy access. I chose =<leader>C=

#+begin_src emacs-lisp
(defun my/config ()
  "Open Doom config in the current frame with config-mode enabled."

  (interactive)
  ;; (find-file "~/.config/doom/config.org")
  (find-file (expand-file-name "config.org" doom-user-dir))
  (my/config-mode 1))

(map! :leader
      :desc "Open Doom config (config-mode)"
      "C" #'my/config)

;;; =========================== END CONFIG MODE ===========================
#+end_src

** Terminal

Within *Nexus*, terminal usage is just as important as the GUI.

Doom handles most of this for us but there's some aspects we still need to change.

First, we enable mouse usage in the terminal

#+begin_src emacs-lisp
(unless (display-graphic-p)
  (xterm-mouse-mode 1)
  (global-set-key (kbd "<mouse-4>") 'scroll-down-line)
  (global-set-key (kbd "<mouse-5>") 'scroll-up-line))

#+end_src

** Benchmark

#+begin_src emacs-lisp
(my/report-time "Core")

#+end_src

* UI

Most of the UI tweaks have been inspired by [[github:rougier/nano-emacs][nano emacs]]. Simple, although not to the extreme of nano, and cohesive layouts with minimal color palettes.

#+begin_src emacs-lisp
(setq my/section-start-time (current-time))

#+end_src

** Font

The default font settings for the nano theme assume the Roboto font, which I personally don't care for. We can change those here.

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "JetBrainsMono Nerd Font" :size 16))

;; fix nerd icons
(after! nerd-icons
  (setq nerd-icons-font-family "JetBrainsMono Nerd Font")
  (set-fontset-font t '(#xe000 . #xf8ff) "JetBrainsMono Nerd Font")
  (set-fontset-font t '(#x23fb . #x23fe) "JetBrainsMono Nerd Font")
  (set-fontset-font t '(#x2665 . #x2665) "JetBrainsMono Nerd Font")
  (set-fontset-font t '#xf000 "JetBrainsMono Nerd Font"))

;; (setq nano-mono)

#+end_src

Then increasing the default line height.

#+begin_src emacs-lisp
(setq-default line-spacing 6)
;; (add-hook 'org-mode-hook (lambda () (setq-default line-spacing 6)))

#+end_src

** Theme

Here we can set the base nano theme

#+begin_src emacs-lisp
(setq doom-theme 'doom-tokyo-night)
(after! doom-themes ;; HACK: corfu complains about circular inheritance
  (custom-theme-set-faces!
   (or doom-theme 'user)
   '(gnus-group-news-low :inherit default)
   '(gnus-group-news-low-empty :inherit gnus-group-news-low)))

;; (require 'nano-base-colors)
;; (require 'nano-faces)
;; (require 'nano-theme)
;; 
;; (nano-mode)
;; (setq doom-theme 'nano-dark)

#+end_src

Then, we can source the outside file =<file name>= which is responsible for manipulating the face colors.

This file, generated by matugen, will maniputlate the main and accent color of nano-dark to match the current matugen theme.

#+begin_quote
   If you do not use =matugen= or simply want to use a different theme
    then you can comment this out
#+end_quote

#+begin_src emacs-lisp

#+end_src

** Layout

Nano offers a different perspective when it comes to editor layouts. It provides more spacing/gaps between windows and creates a layout that feels comfortable and easier to intake visually.

We capitalize on this by using some of the Nano defaults

First, we increase the padding on frames

#+begin_src emacs-lisp
(setq default-frame-alist
      (append (list
               '(min-height . 1)
               '(height     . 45)
               '(min-width  . 1)
               '(width      . 81)
               '(vertical-scroll-bars . nil)
               '(internal-border-width . 20)
               '(left-fringe    . 8)
               '(right-fringe   . 8)
               '(tool-bar-lines . 0)
               '(menu-bar-lines . 0))))

#+end_src

Then we increase the gap between windows

#+begin_src emacs-lisp
(setq window-divider-default-right-width 24)
#+end_src

We also need to change the face value for the gap between windows. However, we need to do this after the theme's set, so we'll need to add a hook function. This will have to happen after the solaire package is activated since it alters face colors.

#+begin_src emacs-lisp
(add-hook 'solaire-mode-hook
          (lambda ()
            (let ((bg (face-background 'default)))
              (dolist (face '(window-divider
                              window-divider-first-pixel
                              window-divider-last-pixel
                              vertical-border))
                (set-face-attribute face nil
                  :foreground bg
                  :background bg
                  :distant-foreground bg
                  :inherit nil))
              (redraw-display))))

#+end_src

** Line Numbers :MODE:HOOK:

I use relative line numbers throughout the editor for easier vim navigation. However, this is mostly useful in code buffers, and not needed in popups, message buffers, etc.

So, we can set the =prog= and =conf= modes to default with line numbers, leaving everything else unchanged

#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
(add-hook 'prog-mode-hook #'display-line-numbers-mode)
(add-hook 'conf-mode-hook #'display-line-numbers-mode)

;; remove org line numbers
(after! org
  (add-hook 'org-mode-hook (lambda () (display-line-numbers-mode 0)))
  (add-hook 'org-agenda-mode-hook (lambda () (display-line-numbers-mode 0)))
  (add-hook 'nano-agenda-mode-hook (lambda () (display-line-numbers-mode 0))))

;; remove for markdown buffers
(add-hook 'gfm-mode-hook (lambda () (display-line-numbers-mode 0)))

#+end_src

** Vertico Posframe

Here we just tweak the positioning and size of the posframe for vertico's completion buffers

#+begin_src emacs-lisp
(use-package! vertico-posframe
  :config
  (setq vertico-posframe-min-width 50
        vertico-posframe-min-height 15
        vertico-posframe-poshandler #'posframe-poshandler-frame-top-center))

#+end_src

** Modeline :HOOK:

The modeline in nano is something that really bought me. Its extemely simple and isn't even a modeline really; Its a headerline with interactive buttons and features depending on the mode you're in.

It also has a nice API for creating new formats, or editing existing ones (althought not documented at all). To take advantage of this we use the =rewrite= branch of the config, as the master branch is far behind this one.

First, we'll add a hook to load nano-modeline. This will have to happen after the theme has been loaded for the faces to be represented accurately. Then we need to conceal the default modeline for every buffer.

#+begin_src emacs-lisp
(add-hook 'doom-load-theme-hook (lambda () (require 'nano-modeline)))
(global-hide-mode-line-mode 1)
;; (add-hook 'after-change-major-mode-hook (lambda () (hide-mode-line-mode 1)))

#+end_src

We can then define some hooks for enabling the modeline

#+begin_src emacs-lisp
;; (add-hook! org-mode #'nano-modeline)

(add-hook! prog-mode #'nano-modeline)
(add-hook! text-mode #'nano-modeline)
(add-hook! messages-buffer-mode #'nano-modeline)
(add-hook 'vterm-mode-hook (lambda ()              ;; special modes require their format
                             (nano-modeline
                              nano-modeline-format-terminal 'header)))

#+end_src

*** Org Mode

Org mode needs a special tweak for its modeline. This is because we enable =olivetti-mode= for centering org buffers.

Nano modeline describes a function =nano-modeline-padding-to= which applies the padding for the alignment of the modeline. However, we need to patch it so that it applies the default face to *both* sides of padding. Otherwise, the background will overflow into the padding of the buffers.

Since its just a small change, I chose to patch the function rather than create a personal fork or pull request.

#+begin_src emacs-lisp
(after! nano-modeline
  (defun nano-modeline-padding-to (&optional left right face)
    "This function returns the left and right padding to precisely align the
mode-line (or header-line) to window, margin, fringe or text extents,
depending on LEFT and RIGHT. LEFT and RIGHT can be constant ('window,
'fringe, 'margin or 'text) or a cons specifying (what . (char-size
. pixel-size)). It returns two strings that must be respectively
prepended and appended to the mode-line (or header-line). An optional
FACE can be given to be used for the prefix and the suffix."

    (let* ((left (or left (car nano-modeline-alignment)))
           (left (if (not (consp left))
                     (cons left '(0 . 0))
                   left))
           (right (or right (cdr nano-modeline-alignment)))
           (right (if (not (consp right))
                      (cons right '(0 . 0))
                    right))
           (face (or face `(:foreground ,(face-foreground 'default)
                            :background ,(face-background 'default)
                            :underline nil :overline nil :inherit nil :box nil))))
      (cons (concat (propertize " " 'display (nano-modeline-align-to 'left 'window) 'face face)
                    (propertize " " 'display
                                (nano-modeline-align-to 'left (car left) (cadr left) (cddr left))
                                'face face))
            (concat (propertize " " 'display
                                (nano-modeline-align-to 'right (car right) (cadr right) (cddr right)))
                    (propertize " " 'display (nano-modeline-align-to 'right 'window) 'face face))))))

#+end_src

** Markdown Rendering

*** Faces

Reading markdown in emacs should be /almost/ as much fun as reading org documents. To accomplish this, we set some custom faces for when inside a markdown file.

First, we'll set the heading sizes

#+begin_src emacs-lisp
(custom-set-faces!
  '(markdown-header-delimiter-face :height 0.9)
  '(markdown-header-face-1 :height 1.8 :weight extra-bold)
  '(markdown-header-face-2 :height 1.4 :weight extra-bold)
  '(markdown-header-face-3 :height 1.2 :weight extra-bold)
  '(markdown-header-face-4 :height 1.15 :weight bold)
  '(markdown-header-face-5 :height 1.1 :weight bold)
  '(markdown-header-face-6 :height 1.05 :weight semi-bold))

#+end_src

*** Custom Callouts :HOOK:

We can also set some custom faces for callouts. We'll use these to create overlays that make callouts more styled.

#+begin_src emacs-lisp
(defface nb/markdown-callout-note
  '((t :background "#1e1e2e" :extend t))
  "Face for NOTE callouts")

(defface nb/markdown-callout-warning
  '((t :background "#3b2f1c"
       :foreground "#fbe1b3"
       :italic t
       :extend t))
  "Face for WARNING callouts")

(defface nb/markdown-callout-important
  '((t :background "#241e2b"
       :foreground "#B87FFF"
       :italic t
       :extend t))
  "Face for IMPORTANT callouts")

(defface nb/markdown-callout-tip
  '((t :background "#1c3624"
       :foreground "#09B43A"
       :italic t
       :extend t))
  "Face for TIP callouts")

#+end_src

Next, we can link those faces to their header names, and include some header alternatives that we can use to override them in our overlay

#+begin_src emacs-lisp
(defun nb/markdown-callout-face (type)
  (pcase type
    ("NOTE"    'nb/markdown-callout-note)
    ("WARNING" 'nb/markdown-callout-warning)
    ("TIP"     'nb/markdown-callout-tip)
    ("IMPORTANT"     'nb/markdown-callout-important)))

(defun nb/markdown-callout-header (type)
  (pcase type
    ("WARNING"       " Warning")
    ("NOTE"          "󰏫 Note")
    ("TIP"           " Tip")
    ("IMPORTANT"     " Important")))

#+end_src

Then, we'll define a bar to replace the =>= characters and a function to do so.

#+begin_src emacs-lisp
;; don't hide by default (markdown-mode)
(setq markdown-blockquote-display-char ">")

(defun nb/markdown-callout-line-bar (pos face)
  (let ((ov (make-overlay pos (1+ pos))))
    (overlay-put ov 'display "┃ ")
    (overlay-put ov 'face face)
    (overlay-put ov 'nb-callout t)
    (overlay-put ov 'evaporate t)))

(defun nb/markdown-callout-replace-header (start end type)
  (let ((ov (make-overlay start end)))
    (overlay-put ov 'display (nb/markdown-callout-header type))
    (overlay-put ov 'face 'bold)
    (overlay-put ov 'nb-callout t)
    (overlay-put ov 'evaporate t)))

#+end_src

We also need a function to clear out any old overlays after they've been created

#+begin_src emacs-lisp
(defun nb/markdown-clear-callout-overlays ()
  (remove-overlays (point-min) (point-max) 'nb-callout t))

#+end_src

To put it all together we'll create the overlays, searching for the header names using regex and applying each of these components; Then hooking it into markdown-mode and watching for buffer changes

#+begin_src emacs-lisp
(defun nb/markdown-apply-callout-overlays ()
  (save-excursion
    (let ((case-fold-search t))
      (goto-char (point-min))
      (nb/markdown-clear-callout-overlays)

      (while (re-search-forward
              "^>\\s-*\\[!\\([a-z]+\\)\\].*\\(?:\n>.*\\)*"
              nil t)
        (let* ((type (upcase (match-string 1)))
               (block-start (match-beginning 0))
               (raw-end (match-end 0))
               (block-end (if (< raw-end (point-max))
                              (1+ raw-end)
                            raw-end))
               (face (nb/markdown-callout-face type)))

          ;; background overlay
          (when face
            (let ((ov (make-overlay block-start block-end)))
              (overlay-put ov 'nb-callout t)
              (overlay-put ov 'face face)
              (overlay-put ov 'evaporate t)))

          ;; walk each line in the block
          (save-excursion
            (goto-char block-start)
            (while (< (point) block-end)
              (when (looking-at "^>\\s-*")
                ;; replace >
                (nb/markdown-callout-line-bar (point) face)

                ;; header replacement
                (when (looking-at "^>\\s-*\\[!\\([a-z]+\\)\\]")
                  (nb/markdown-callout-replace-header
                   (match-beginning 0)
                   (match-end 0)
                   type)))
              (forward-line 1))))))))

#+end_src

#+begin_src emacs-lisp
(defun nb/markdown-refresh-callouts (&rest _)
  (when (derived-mode-p 'markdown-mode)
    (nb/markdown-apply-callout-overlays)))

;; refresh on buffer change
(add-hook 'markdown-mode-hook
          (lambda ()
            (nb/markdown-apply-callout-overlays)
            (add-hook 'after-change-functions
                      #'nb/markdown-refresh-callouts
                      nil t)))

#+end_src

*** Hiding Elements :HOOK:

Here, we have a functions which describe how to hide elements (like header marks) when editing markdown docs, while showing the elements when editing that line

#+begin_src emacs-lisp
 (defvar nb/current-line '(0 . 0)
   "(start . end) of current line in current buffer")
 (make-variable-buffer-local 'nb/current-line)

 (defun nb/unhide-current-line (limit)
   "Font-lock function"
   (let ((start (max (point) (car nb/current-line)))
         (end (min limit (cdr nb/current-line))))
     (when (< start end)
       (remove-text-properties start end
                       '(invisible t display "" composition ""))
       (goto-char limit)
       t)))

 (defun nb/refontify-on-linemove ()
   "Post-command-hook"
   (let* ((start (line-beginning-position))
          (end (line-beginning-position 2))
          (needs-update (not (equal start (car nb/current-line)))))
     (setq nb/current-line (cons start end))
     (when needs-update
       (font-lock-flush))))

 (defun nb/markdown-unhighlight ()
   "Enable markdown concealling"
   (interactive)
   (markdown-toggle-markup-hiding 'toggle)
   (font-lock-add-keywords nil '((nb/unhide-current-line)) t)
   (add-hook 'post-command-hook #'nb/refontify-on-linemove nil t))

#+end_src

Then we hook that into =markdown-mode=

#+begin_src emacs-lisp
(add-hook 'markdown-mode-hook #'nb/markdown-unhighlight)

#+end_src

** Benchmark

#+begin_src emacs-lisp
(my/report-time "UI")

#+end_src

* Editor

#+begin_src emacs-lisp
(setq my/section-start-time (current-time))

#+end_src

** Dired Replacement :BINDING:

We replace dired with [[github:alexluigit/dirvish][dirvish]] as it comes with better defaults and better UI. So we install this using the =package!= macro within the [[file:packages.el][packages.el]] file

#+begin_src emacs-lisp :tangle "packages.el"
(package! dirvish)

#+end_src

Then we can configure it within [[file:config.el][config.el]]

#+begin_src emacs-lisp
(use-package! dirvish
  :defer t
  :hook
  (emacs-startup . dirvish-override-dired-mode)        ;; override dired
  (dired-mode . (lambda () (display-line-numbers-mode 0)))  ;; no numbers

  :custom
  (dirvish-quick-access-entries
   '(("d" "~/Downloads/"                "Downloads")
     ("p" "~/Projects"                  "Projects")
     ("c" "~/.config"                   "Configs")
     ("i" "~/Pictures"                  "Pictures")
     ("s" "~/scripts"                   "Scripts")
     ("m" "/mnt/"                       "Drives")
     ("e" "/sudo:root@localhost:/etc"   "Modify program settings")))

  :config
  ;; core modes
  (dirvish-peek-mode)
  (dirvish-side-follow-mode)

  ;; bindings
  (define-key dired-mode-map (kbd "a") #'dired-create-empty-file)

  ;; use 'eza' for previews
  (dirvish-define-preview eza (file)
    "Use `eza' to generate directory preview."
    :require ("eza")
    (when (file-directory-p file)
      `(shell . ("eza" "--color=always" "--icons=always"
                 "--group-directories-first" ,file))))
  (push 'eza dirvish-preview-dispatchers))

;; keymaps
(after! dirvish
  (map! :map dirvish-mode-map
        :n "a" #'dired-create-empty-file))

#+end_src

Then we can override dired by replacing its default mapping

#+begin_src emacs-lisp
(map! :leader
      :desc "Open Dirvish"
      "o-" #'dirvish)

#+end_src

** Org Tweaks

*** Core :HOOK:

Here, we'll set =org-mode='s core behavior and ui.

First we'll change the header sizes accordingly

#+begin_src emacs-lisp
(custom-set-faces!
 '(org-level-1 :height 1.5 :weight extra-bold)
 '(org-level-2 :height 1.3 :weight extra-bold)
 '(org-level-3 :height 1.1 :weight bold)
 '(org-level-4 :height 1.0 :weight bold)
 '(org-level-5 :height 0.95 :weight semi-bold))

#+end_src

Then, we'll change some of the =org-modern= featues

#+begin_src emacs-lisp
(with-eval-after-load 'org
  (add-hook 'org-mode-hook (lambda () (diff-hl-mode 0)))
  (setq
   org-modern-star 'replace                             ;; header style
   org-modern-replace-stars "◉○◈◇✳"                     ;; header replacement
   org-modern-fold-stars nil                            ;; fold settings
   org-modern-list '((?- . "•") (?+ . "◦") (?* . "◆"))  ;; list replacements
   org-startup-with-inline-images t                     ;; default images
   org-startup-with-latex-preview t                     ;; default latex
   org-hide-emphasis-markers t                          ;; no markers
   org-pretty-entities t)                               ;; enable modern style
  (global-org-modern-mode))                             ;; every org file

#+end_src

And include the =org-roam-ui= package into [[file:packages.el][packages.el]]

#+begin_src emacs-lisp :tangle "packages.el"
(package! org-roam-ui)

#+end_src

#+begin_src emacs-lisp
(use-package! org-roam-ui
  :commands (org-roam-ui-open org-roam-ui-mode)
  :config
  (setq org-roam-ui-sync-theme t
        org-roam-ui-follow t
        org-roam-ui-update-on-save t
        org-roam-ui-open-on-start t))

#+end_src

We also need to update the org and org-roam default locations

#+begin_src emacs-lisp
(setq org-directory "~/org")
(setq org-roam-directory "~/org")

#+end_src

Another handy tool I use is [[github:alphapapa/org-ql][org-ql]]. We'll install this into [[file:packages.el][packages.el]]

#+begin_src emacs-lisp :tangle "packages.el"
(package! org-ql)

#+end_src

#+begin_src emacs-lisp
(use-package! orq-ql
  :defer t)

#+end_src

Lastly, we need to package the =djvu= and =nov= packages for =org-noter=

#+begin_src emacs-lisp :tangle "packages.el"
(package! djvu)
(package! nov)

#+end_src


*** Layout

Typically I use a centered layout when reading and editing org documents. For this we use the [[github:rnkn/olivetti][olivetti]] package

We'll start by installing it into the [[file:packages.el][packages.el]] file

#+begin_src emacs-lisp :tangle "packages.el"
(package! olivetti)

#+end_src

Then configure it to a fixed width and hook it into org-mode. However, we don't want it enabled when using =config-mode= so we'll need to handle that as well.

#+begin_src emacs-lisp
(defun my/org-enable-olivetti ()
  "Enable olivetti except in config.org"
  (unless (string-match-p "^config\\.org" (buffer-name))
    (olivetti-mode 1)))

(use-package! olivetti
  :hook
  (org-mode . my/org-enable-olivetti)
  (nano-agenda-mode . olivetti-mode)
  :config
  (setq olivetti-body-width 75))

#+end_src

*** Captures

**** Projects

Projects in org mode are directory independent, stored under =Projects/<project-name>= within the org-directory. Within this directory there is 2 key files: =overview.org= and =tasks.org=. The overview is where the core project goal is as well as requirements, etc. and the tasks file holds all of the tasks for the given project. Each project will also include a =logs= directory for logging progress, debugging, etc.

To make project creation easier we first create a custom function to
1. Prompt for the project name and (optionally) subject
2. Create project directory
3. Populate project directory with files and boiler plate

#+begin_src emacs-lisp
;; used to replace spaces and hypens in project name for file tag
(defun my/slugify (s)
  (replace-regexp-in-string
   "[^a-zA-Z0-9]"
   "_"
   s))

(defun my/org-roam-create-project (name subject)
  "Create a new org project with NAME.
   Optionally add SUBJECT as a filetag if non-empty."
  (interactive
   (list
    (read-string "Project name: ")
    (read-string "Subject (optional): ")))

  (let* ((roam-dir (file-name-as-directory org-roam-directory))
         (base-dir (expand-file-name "Projects/" roam-dir))
         (project-dir (expand-file-name name base-dir))
         (logs-dir (expand-file-name "logs/" project-dir))
         (overview-file (expand-file-name "overview.org" project-dir))
         (tasks-file (expand-file-name "tasks.org" project-dir))
         (slug-name (my/slugify name))
         (slug-subject (unless (string-empty-p subject)
                         (my/slugify subject)))
         (filetags (concat ":project:" slug-name ":"
                           (when slug-subject
                             (concat slug-subject ":")))))

    (make-directory logs-dir t)

    (unless (file-exists-p overview-file)
      (with-temp-file overview-file
        (insert ":PROPERTIES:\n")
        (insert ":ID: " (org-id-uuid) "\n")
        (insert ":END:\n")
        (insert "#+TITLE: " name " Overview\n")
        (insert "#+FILETAGS: " filetags "\n\n")
        (insert "* Overview\n\n")
        (insert "* Tasks\n\n")
        (insert "* Attachments\n\n")))

    (unless (file-exists-p tasks-file)
      (with-temp-file tasks-file
        (insert ":PROPERTIES:\n")
        (insert ":ID: " (org-id-uuid) "\n")
        (insert ":END:\n")
        (insert "#+TITLE: " name " Tasks\n")
        (insert "#+FILETAGS: :project:" slug-name ":tasks:\n\n")
        (insert "* TODO Initial task\n")))

    (org-roam-db-sync)
    (find-file overview-file)
    (message "Org-roam project '%s' created successfully!" name)))

#+end_src

Then we can bind this function to its own keybinding

#+begin_src emacs-lisp
(map! :leader
      :desc "Create new project"
      "np" #'my/org-roam-create-project)

#+end_src

Next, we need a way of quickly extending/creating the log files per project. We'll make a function which does the following:
1. Prompts to select from available projects
2. Captures and stores the project name
3. Returns the log file path

#+begin_src emacs-lisp
;; variables returned by helper functions
(defvar my/org-roam--current-project nil)
(defvar my/org-roam--current-slug nil)

(defun my/org-roam-project-log-path (node)
  (let* ((project
          (completing-read
           "Project: "
           (directory-files
            (expand-file-name "Projects/" org-roam-directory)
            nil "^[^.]")))
         (slug (my/slugify project))
         (date (format-time-string "%Y-%-m-%-d"))
         (logs-dir (expand-file-name
                    (concat "Projects/" project "/logs/")
                    org-roam-directory)))

    (setq my/org-roam--current-project project)
    (setq my/org-roam--current-slug slug)

    (make-directory logs-dir t)
    (expand-file-name (concat date ".org") logs-dir)))

;; NOTE: needed since I can't figure out how to store vars
;; in the 'org-roam-capture--info' list
(defun my/org-roam-current-project (node)
  my/org-roam--current-project)

(defun my/org-roam-current-slug (node)
  my/org-roam--current-slug)

#+end_src

Then we can add it to the =org-roam-capture-templates= list

#+begin_src emacs-lisp
(after! org-roam
  (add-to-list 'org-roam-capture-templates ;; add project prefix
               '("p" "Project"))
  (add-to-list 'org-roam-capture-templates
   '("pl" "Project log" entry
     "\n* %<%H:%M>\n\n%?"
     :target
     (file+head "${my/org-roam-project-log-path}"
                "#+TITLE: %<%Y-%-m-%-d> ${my/org-roam-current-project} log\n#+FILETAGS: :devlog:project:${my/org-roam-current-slug}:\n\n")
     :empty-lines 1)))

#+end_src

Lastly we define a capture for inserting new tasks for a selected project, following most of the same steps as the log capture above.

We define the function

#+begin_src emacs-lisp
(defun my/org-roam-project-task-path (node)
  (let* ((project
          (completing-read
           "Project: "
           (directory-files
            (expand-file-name "Projects/" org-roam-directory)
            nil "^[^.]")))
         (project-dir (concat (expand-file-name "Projects/" org-roam-directory) project))
         (slug (my/slugify project)))

    (setq my/org-roam--current-project project)
    (setq my/org-roam--current-slug slug)

    (expand-file-name "tasks.org" project-dir)))

#+end_src

and then add a capture template

#+begin_src emacs-lisp
(after! org-roam
  (add-to-list
   'org-roam-capture-templates
   '("pt" "Project task" entry
     "* TODO %?"
     :target
     (file+head "${my/org-roam-project-task-path}"
                "#+TITLE: ${my/org-roam-current-project} Tasks\n#+FILETAGS: :tasks:project:${my/org-roam-current-slug}:\n\n")
     :empty-lines 1)))

#+end_src

**** Learning

When it comes to learning, I structure my note taking in a pipeline. The pipeline looks like this:

1. Source notes
   These will be in the =Source= directory and taken alongside the consumed media. They're named after the media as well (i.e =<Book Title.org>=) and will contain quick annotations over the main topics (often with links to the relevant information). These can also be taken on paper.
   
2. Refined notes
   Placed within the =Refined= directory, these notes build off of the source notes. Taking the quick notes and transforming them into fleshed out ideas in your own words and segmenting out key ideas and important vocab words. They will also inherit the same name as the mentioned source note.

3. Permanent notes
   This is the final stage where the main ideas from the previous refined note(s) are put into their own concept. Each permanent note should be a single topic (i.e =Types of Data Modeling.org=). You should be able to explain the topic in a way simple enough for others to understand and paraphrase in a concise mannor. Although the note may be created from one refined note, it can also be extended with information from other notes; This is also where the linking of ideas and other topics comes in.

Each subtopic will also contain its own MOC note (Map-Of-Content). Here we will query the permanent notes for nodes which contain the topics file tag.

In total the structure of the directories will become:

#+begin_src emacs-lisp :tangle no
org
├── Learning
│   ├── Assets
│   ├── MOC
│   ├── Permanent
│   ├── Refined
│   ├── Source
│   └── Vocab
#+end_src

Now we create captures for each type.

#+begin_src emacs-lisp
;; NOTE: these functions will be used to query for
;; subject tags throughout the templates
(defun my/org-roam-list-tags ()
  "Return a list of all unique filetags used across org-roam files."
  (mapcar #'car (org-roam-db-query
                 [:select :distinct [tag]
                  :from tags])))

(defvar my/org-roam-current-tags
  "Stores the last raw selected tags for capture")

(defun my/org-roam-prompt-tags (node)
  "Prompt for filetags with completion, returning colon-separated tags."
  (let* ((input (completing-read "Subject tag: " (my/org-roam-list-tags)))
         (tags (mapconcat #'identity (split-string input " " t) ":")))
    (if (string-empty-p tags)
        ""
      (setq my/org-roam-current-tags input)
      (concat tags ":"))))

(defun my/org-roam-get-tags (node)
    my/org-roam-current-tags)

#+end_src

#+begin_src emacs-lisp
(after! org-roam
  (add-to-list 'org-roam-capture-templates ;; set the learning prefix
               '("l" "Learning"))
  
  (add-to-list 'org-roam-capture-templates
               '("ls" "New source note" plain "%?"
                 :target (file+head "Learning/Source/${slug}.org"
                                    "#+TITLE: ${title}\n#+FILETAGS: :source:${my/org-roam-prompt-tags}")
                 :unnarrowed t))
  
  (add-to-list 'org-roam-capture-templates
               '("lr" "New refined note" plain "%?"
                 :target (file+head "Learning/Refined/${slug}.org"
                                    "#+TITLE: ${title}\n#+FILETAGS: :refined:${my/org-roam-prompt-tags}")
                 :unnarrowed t))

  (add-to-list 'org-roam-capture-templates
               '("lp" "New permenant note" plain
                 "#+TITLE: ${title}\n#+FILETAGS: :permanent:${my/org-roam-prompt-tags}\n\n%?\n\n*** Related Ideas\n\n\n*** Lit Notes\n\n"
                 :target (file+head "Learning/Permanent/${slug}.org" "")
                 :unnarrowed t))

  (add-to-list 'org-roam-capture-templates
               '("lv" "New vocab note" plain
                 "#+TITLE: ${title}\n#+FILETAGS: :vocab:${my/org-roam-prompt-tags}\n\n* Definition\n\n%?\n\n* Examples\n\n"
                 :target (file+head "Learning/Vocab/${slug}.org" "")
                 :unnarrowed t)))

#+end_src

To generate the MOC files, we need to create a custom =dblock= function. It will query first for all notes with a permanent tag, then filter them so that they match all given tags.

#+begin_src emacs-lisp
(defun org-dblock-write:roam-moc (params)
  "Query across permanent notes for given tag(s)"
  (let* ((tags-input (plist-get params :tags))
         (tags (split-string (format "%s" tags-input) " " t))
         (all-tags (cons "permanent" tags))
         (results (org-roam-db-query
                   [:select [n:title n:file t:tag]
                    :from tags t
                    :join nodes n :on (= t:node-id n:id)
                    :where (in t:tag $v1)]
                   (apply #'vector all-tags)))
         (grouped (seq-group-by #'car (mapcar (lambda (r) (list (cadr r) (car r) (caddr r))) results)))
         (matched (cl-remove-if-not
                   (lambda (group)
                     (let ((node-tags (mapcar #'caddr (cdr group))))
                       (cl-every (lambda (tag) (member tag node-tags)) all-tags)))
                   grouped)))
    (dolist (group matched)
      (let ((file (caar (cdr group)))
            (title (cadar (cdr group))))
        (insert (format "- [[file:%s][%s]]\n" file title))))))

#+end_src

Then all we need is a simple capture to insert this block, which will be updated when entering the file.

#+begin_src emacs-lisp
(after! org-roam
  (add-to-list 'org-roam-capture-templates
               '("lm" "New MOC" plain
                 "#+TITLE: ${title}\n#+FILETAGS: :MOC:${my/org-roam-prompt-tags}\n\n%?#+BEGIN: roam-moc :tags \"${my/org-roam-get-tags}\"\n#+END:"
                 :target (file+head "Learning/MOC/${slug}.org" "")
                 :unnarrowed t)))

#+end_src


*** Agenda

Next we'll setup the agendas. We'll start by installing the [[github:rougier/nano-agenda][nano-agenda]] and [[github:alphapapa/org-super-agenda][super-agenda]] packages using [[file:packages.el][packages.el]]

#+begin_src emacs-lisp :tangle "packages.el"
(package! nano-agenda
  :recipe (:type git
           :host github
           :repo "rougier/nano-agenda"
           :branch "rewrite"))

(package! org-super-agenda)

#+end_src

Then we can configure them, starting with nano-agenda

#+begin_src emacs-lisp
(use-package! nano-agenda
  :after org
  :config
  (setq nano-agenda-header-show nil)) ;; we set our own in the 'UI -> Modeline' section

#+end_src

And moving onto super-agenda

#+begin_src emacs-lisp
(use-package! org-super-agenda
  :after org
  :config
  (org-super-agenda-mode))

#+end_src

We'll also need to set the =org-agenda-files=. I set it to the entire directory recursively due to the way my layout is setup.

#+begin_src emacs-lisp
(setq org-agenda-files
      (directory-files-recursively "~/org" "\\.org$"))

#+end_src

** Vterm Tweaks :HOOK:BINDING:

Here we make some configuration tweaks to vterm windows and its behavior.

We'll start by editing the window UI. First, we'll disable line numbers for the vterm buffer and revert the default line-spacing to 1.

#+begin_src emacs-lisp
(add-hook 'vterm-mode-hook (lambda ()
                             (display-line-numbers-mode 0)
                             (setq-local line-spacing 0)))

;; (add-hook 'vterm-mode-hook (lambda ()
;;                              (display-line-numbers-mode 0)
;;                              (setq-local line-spacing 0)
;;                              (face-remap-add-relative 'default :height 100)))

#+end_src

Next we'll focus on the behavior of vterm. Thanks to the keybindings later, I never really need to have =ESC= mapped to emacs when in vterm. So we'll toggle that automatically

#+begin_src emacs-lisp
(add-hook 'vterm-mode-hook (lambda ()
                             (evil-collection-vterm-toggle-send-escape)))

#+end_src

And then we'll set some QoL keybindings. First up, toggling the vterm popup.

Since vterm won't allow us to have a single global keybinding, we'll have to bind it to a fake prefix globally and then translate the =C-e= binding to call this instead

#+begin_src emacs-lisp
(define-key key-translation-map (kbd "C-e") (kbd "<f20>"))
(map! :g "<f20>" #'+vterm/toggle)

#+end_src

Then, we can define some keymaps for working within the terminal

#+begin_src emacs-lisp
(after! vterm
  ;; unbind M-<num> for switching workspaces
  (dotimes (i 10)
    (define-key vterm-mode-map (kbd (format "M-%d" i)) nil))
  ;; remove C-h from keymap exceptions
  (setq vterm-keymap-exceptions (delete "C-h" vterm-keymap-exceptions))
  (define-key vterm-mode-map (kbd "C-h") #'vterm--self-insert))

#+end_src

I also like to have a =posframe= popup option for using the terminal. This will be a floating window in the middle of the screen, toggled using a keybind

The function itself is pretty simple. We create frame if one doesn't exist, toggle the frame if it does

#+begin_src emacs-lisp
(defun my/vterm-posframe-toggle ()
  "Toggle a floating vterm in a posframe."
  (interactive)
  (let* ((buf-name "*vterm-posframe*")
         (buf (get-buffer buf-name))
         (pframe (and buf (buffer-local-value 'posframe--frame buf))))
    (cond

     ((and pframe (frame-live-p pframe) (frame-visible-p pframe))
      (posframe-hide buf-name))

     ((and pframe (frame-live-p pframe))
      (posframe-show buf-name
                     :poshandler #'posframe-poshandler-frame-center
                     :width 100
                     :height 30
                     :border-width 5
                     :background-color "#1e2127"
                     :accept-focus t)
      (select-frame-set-input-focus pframe))

     (t
      (unless buf
        (with-current-buffer (get-buffer-create buf-name)
          (vterm-mode)))
      (let ((new-frame (posframe-show buf-name
                                      :poshandler #'posframe-poshandler-frame-center
                                      :width 100
                                      :height 30
                                      :border-width 5
                                      :background-color "#1e2127"
                                      :accept-focus t)))
        ;; allow time to initialize frame before focus
        (run-with-timer 0.2 nil #'select-frame-set-input-focus new-frame))))))

#+end_src

Since this is less likely to be used as much, we can globally bind it to a =C-c= prefix mapping

#+begin_src emacs-lisp
(map! :g :desc "Toggle vterm posframe" "C-c t" #'my/vterm-posframe-toggle)
;; (global-set-key (kbd "C-c t") #'my/vterm-posframe-toggle)

#+end_src

** Languages/LSP

*Nexus* uses =lsp-mode= over =eglot= for managing and configuring LSPs. This choice is due to:

1. =lsp-mode= offers using =config.json= and =launch.json= files - This makes a projects configuration more accessible to people using other editors

2. Ease of configuraiton - Setting up new LSPs or configuring existing ones is easier. Plus there is usually an auto install prompt for LSPs which aren't on the current system.

3. UI - The =lsp-ui= package makes browsing definitions and references much prettier

*** Hyprlang :HOOK:

Hyprland's config language isn't outright supported by most packages, so we'll have to manually add all of the behavior.

We'll start by installing =hyprlang-ts-mode= using [[file:packages.el][packages.el]]

#+begin_src emacs-lisp :tangle "packages.el"
(package! hyprlang-ts-mode)

#+end_src

Then configuring it to activate on hypr files, and adding it to our tree-sitter source list

#+begin_src emacs-lisp
(defun my-hyprlang-detect ()
  "Activate hyprlang-ts-mode for any .conf file in a hypr/ directory."
  (when (and buffer-file-name
             (string-match-p "/hypr/.*\\.conf\\'" buffer-file-name))
    (require 'hyprlang-ts-mode)
    (hyprlang-ts-mode)))

(add-hook 'find-file-hook #'my-hyprlang-detect)

(after! treesit
  (add-to-list 'treesit-language-source-alist
               '(hyprlang "https://github.com/tree-sitter-grammars/tree-sitter-hyprlang")))

#+end_src

#+BEGIN_QUOTE
   You may need to manually install the grammar before using it
    =M-x treesit-install-language-grammar= -> =hyprlang=
#+END_QUOTE

To use the community LSP for hyprland config files, hyprls, we have to add it to our LSP config

#+BEGIN_QUOTE
   If you do not have the [[github:hyprland-community/hyprls][hyprls]] package, youll need to install it
#+END_QUOTE

#+begin_src emacs-lisp
(after! lsp-mode
  (add-to-list 'lsp-language-id-configuration '(hyprlang-ts-mode . "hyprlang"))
  (lsp-register-client
   (make-lsp-client
    :new-connection (lsp-stdio-connection '("hyprls"))
    :activation-fn (lsp-activate-on "hyprlang")
    :server-id 'hyprls))
  (add-hook 'hyprlang-ts-mode-hook #'lsp-deferred))

#+end_src

*** SQL

Since Doom doesn't bundle an SQL LSP by default, we'll need to configure the builtin one form =lsp-mode=

#+begin_src emacs-lisp
(add-hook 'sql-mode-hook 'lsp-deferred)
(after! lsp-mode
  ;; connection configuration is handled by a .sqls/config.json file in
  ;; the project root. see https://emacs-lsp.github.io/lsp-mode/page/lsp-sqls
  (setq lsp-sqls-workspace-config-path "root"))

#+end_src

#+BEGIN_QUOTE
   If you do not have the [[github:sqls-server/sqls][sqls]] package, you'll need to install it
#+END_QUOTE

For a proper database client, *Nexus* employs the [[github:kostafey/ejc-sql][ejc-sql]] package. Although =sqls= is /capable/ of executing queries, it fails in comparison to =ejc=.

We'll first package it into [[file:packages.el][packages.el]] then hook it into =sql-mode=

#+begin_src emacs-lisp :tangle "packages.el"
(package! ejc-sql)

#+end_src

On top of that, a custom function to suppress org-element warnings from within the results buffer. Otherwise, using the =org-export-table= command will result in a warning every time. We also set some other defaults for the result window here

#+begin_src emacs-lisp
(defun ejc-suppress-org-element-warning ()
  (setq-local warning-suppress-types '((org-element))))

(use-package! ejc-sql
  :hook
  (sql-mode . ejc-sql-mode)
  (ejc-result-mode . ejc-suppress-org-element-warning)
  (ejc-result-mode . hide-mode-line-mode)
  :defer t)

(after! ejc-sql
  (set-popup-rule!
    "^\\*ejc-sql-output*"
    :side 'bottom
    :height 10
    :select t
    :quit 'current))

#+end_src

*** Docsets :HOOK:

Although not always necessary its nice to have offline documentation available when internet access is either unstable or not available.

Doom includes an optional module for installing the =dash-docs= package which we can configure here.

The first step is to include a list of docsets which are always installed.

#+BEGIN_QUOTE
   You may wish to edit this list to fit your needs
#+END_QUOTE

#+begin_src emacs-lisp
(defvar my/dash-docsets
  '("Python" "Go" "Rust" "C" "C++" "JavaScript"
    "TypeScript" "R" "Qt" "SQLite" "PostgreSQL")
  "Docsets to ensure are installed.")

(defun my/dash-docs-ensure-installed ()
  "Install any docsets from my/dash-docsets that aren't already present."
  (interactive)
  (require 'dash-docs)
  (dolist (docset my/dash-docsets)
    (let ((docset-path (expand-file-name
                        (concat docset ".docset")
                        dash-docs-docsets-path)))
      (unless (file-directory-p docset-path)
        (message "Installing docset: %s" docset)
        (dash-docs-install-docset docset)))))

#+end_src

You can then run =M-x my/dash-docs-ensure-installed= within an emacs session to install all the required docs in one go.

Next we conditionally activate docsets based on the mode

#+begin_src emacs-lisp
(defvar my/dash-mode-docsets
  '((python-mode        . ("Python"))
    (go-mode            . ("Go"))
    (ess-r-mode         . ("R"))
    (sql-mode           . ("SQLite" "PostgreSQL"))
    (rust-mode          . ("Rust"))
    (c-mode             . ("C" "C++"))
    (c++-mode           . ("C++"))
    (js-mode            . ("JavaScript"))
    (typescript-mode    . ("TypeScript" "JavaScript")))
  "Alist mapping major modes to their dash docsets.")

(defun my/dash-set-docsets ()
  "Set buffer-local docsets based on major mode."
  (when-let ((docsets (alist-get major-mode my/dash-mode-docsets)))
    (setq-local consult-dash-docsets docsets)))

(add-hook 'prog-mode-hook #'my/dash-set-docsets)

#+end_src

Finally, we set the browser function to use =EAF= (setup later in the =Editor -> EAF= section). If you choose not to use =EAF= then you'll need to modify or remove this change (default is =eww=)

#+begin_src emacs-lisp
(after! dash-docs
  (setq dash-docs-browser-func #'eaf-open-browser-other-window))

#+end_src


** Mu4e

I use mu4e extensively. So it's a no brainer we configure it. The address used should be set within the =secrets.el= file discussed in the earlier =Core -> Secrets= section.

*** Dashboard

We start by installing the [[github:rougier/mu4e-dashboard][mu4e-dashboard]] package into [[file:packages.el][packages.el]]

#+begin_src emacs-lisp :tangle "packages.el"
(package! mu4e-dashboard
  :recipe (:host github
           :repo "rougier/mu4e-dashboard"))

#+end_src

We also need to set some custom options to make links play nice. We define some helper functions which force links in the dashboard file to open within an existing instance of the headers buffer.

#+begin_src emacs-lisp 
(defun my/mu4e-search-in-headers-window (query)
  "Run mu4e QUERY in existing *mu4e-headers* window."
  (interactive)
  (let ((headers-win (get-buffer-window "*mu4e-headers*")))
    (if headers-win
        (with-selected-window headers-win
          (mu4e-headers-search query))
      ;; fallback if headers window doesn't exist
      (mu4e-headers-search query))))

(defun my/mu4e-dashboard-org-open-at-point (&rest _args)
  "Handle RET on mu4e-dashboard links."
  (let* ((link (org-element-lineage
                (org-element-context)
                '(link)
                t)))
    (when (and link
               (string= (org-element-property :type link) "mu"))
      (my/mu4e-search-in-headers-window
       (org-element-property :path link))
      t)))

;; setup function to apply tweaks
(defun my/mu4e-dashboard-setup ()
  (interactive)
  (setq-local org-return-follows-link nil)
  (add-hook 'org-open-at-point-functions
            #'my/mu4e-dashboard-org-open-at-point nil t))

#+end_src

Next we need to set the path to the [[file:mu4e-sidebar.org][dashboard file]], apply the link tweaks and keybindings

#+begin_quote
   If you wish to change the dashboard, you can find the docs in the [[github:rougier/mu4e-dashboard][repo]]
#+end_quote

#+begin_src emacs-lisp
(use-package! mu4e-dashboard
  :after mu4e
  :config
  (add-hook 'mu4e-dashboard-mode-hook #'my/mu4e-dashboard-setup)
  (add-hook 'mu4e-dashboard-mode-hook (lambda () (diff-hl-mode 0)))
  (setq mu4e-dashboard-file (expand-file-name "mu4e-sidebar.org" doom-user-dir))
  :defer 0)

#+end_src


*** UI :HOOK:

The UI changes are pretty minimal. We need to first add the headerline using =nano-modeline=

#+begin_src emacs-lisp
;; special case for headers-mode
;; (after! mu4e
;;   (add-hook 'buffer-list-update-hook
;;             (lambda ()
;;               (when (derived-mode-p 'mu4e-headers-mode)
;;                 (nano-modeline nano-modeline-format-mu4e-headers 'header)))))
;; 
;; (after! mu4e
;;   (add-hook 'mu4e-view-mode-hook (lambda ()
;;                                    (nano-modeline nano-modeline-format-mu4e-message 'header)))
;;   (add-hook 'mu4e-compose-mode-hook (lambda ()
;;                                    (nano-modeline nano-modeline-format-mu4e-headers 'header))))

#+end_src

Then, setup a default layout for automated window placement

#+begin_src emacs-lisp
;; change if necessary
(defvar my/mu4e-default-query "m:/gmail/inbox"
  "Default mu4e search query used when opening mu4e.")

(defun my/mu4e-default-layout ()
  "Open mu4e with dashboard sidebar and default query."
  (interactive)
  (delete-other-windows)
  (mu4e t)
  (require 'mu4e-dashboard)
  (mu4e-headers-search my/mu4e-default-query)
  (let* ((headers-window (selected-window))
         (sidebar-window (split-window headers-window nil 'left)))
    (window-resize sidebar-window
                   (- 35 (window-width sidebar-window))
                   t)
    (with-selected-window sidebar-window
      (find-file mu4e-dashboard-file)
      (mu4e-dashboard-mode)
      (set-window-dedicated-p sidebar-window t))
    (select-window headers-window)))

#+end_src

And a custom binding for it

#+begin_src emacs-lisp
(map! :leader :desc "Mu4e Default Layout" "oM" #'my/mu4e-default-layout)

#+end_src

** Debugger 

*** Base :BINDING:

By default, Doom will use =eglot-mode= and pair it with =dape= for debugging. However, since we use =lsp-mode= instead, we'll need to confgure =dap-mode= to work along side it.

We'll start by defining the =dap-mode= package in [[file:packages.el][packages.el]]

#+begin_src emacs-lisp :tangle "packages.el"
(package! dap-mode)

#+end_src

Then we can configure its base behavior (loading it after =lsp-mode=)

#+begin_src emacs-lisp
(use-package! dap-mode
  :after lsp-mode
  :config
  (dap-mode 1)
  (dap-ui-mode 1)
  (dap-tooltip-mode 1)
  (dap-ui-controls-mode 1))

#+end_src

And define some base keybindings before going into debugger specific configurations

#+begin_src emacs-lisp
(after! dap-mode
  (map! :leader
        :desc "Toggle breakpoint"
        "db" #'dap-breakpoint-toggle)
  (map! :leader
        :desc "Toggle debugger"
        "dd" #'dap-debug)
  (map! :leader
        :desc "Disconnect debugger"
        "dx" #'dap-disconnect)
  (map! :leader
        :desc "Restart debugger"
        "dr" #'dap-debug-restart)
  (map! :leader
        :desc "Toggle REPL"
        "dt" #'dap-ui-repl)
  (map! :leader
        :desc "DAP eval"
        "de" #'dap-eval)
  (map! :leader
        :desc "DAP eval region"
        "dE" #'dap-eval-region)
  (map! :leader
        :desc "Next"
        "dn" #'dap-next)
  (map! :leader
        :desc "Step in"
        "di" #'dap-step-in)
  (map! :leader
        :desc "Step out"
        "do" #'dap-step-out)
  (map! :leader
        :desc "Continue"
        "dc" #'dap-continue))

#+end_src

*** cpp-tools :HOOK:

We'll require based on the mode. For cpp-tools we only focus on the base C/C++ modes and their tree-sitter counter parts.

#+begin_src emacs-lisp
(add-hook 'c-mode-hook (lambda ()
                         (require 'dap-cpptools)))
(add-hook 'c++-mode-hook (lambda ()
                           (require 'dap-cpptools)))
(add-hook 'c-ts-mode-hook (lambda ()
                            (require 'dap-cpptools)))
(add-hook 'c++-ts-mode-hook (lambda ()
                              (require 'dap-cpptools)))

#+end_src

** EAF

[[github:emacs-eaf/emacs-application-framework][EAF]] (Emacs Application Framework) is an extensible framework for upgrading the graphical capabilities of emacs.

Its /extremely/ useful in my workflow and helps extend things like:

- HTML email rendering
- Simple web browsing
- Viewing .mp4 files

And more. To install you'll need to follow the [[https://github.com/emacs-eaf/emacs-application-framework?tab=readme-ov-file#install][instructions from the repository]] as building with straight is not recommended.

After installing, we can set the load path and require the desired package(s) with =use-package=

#+BEGIN_QUOTE
  Depending on where you clone the repo, you will need to change the
   =load-path= variable or else it won't work. You may also need to
   remove some of the required packages depending on what you chose
   to install
#+END_QUOTE

#+begin_src emacs-lisp
(defun my/close-eaf-window ()
  "Kills current EAF process and closes its window"
  (interactive)
  (eaf-kill-process)
  (delete-window))

(use-package! eaf
  :load-path "~/src/emacs-eaf"  ;; XXX: change to repo location
  :defer 0
  :config
  (require 'eaf)
  (require 'eaf-browser)
  (require 'eaf-pdf-viewer)
  (require 'eaf-map)
  (require 'eaf-music-player)
  
  (define-key eaf-mode-map* (kbd "C-c q") #'my/close-eaf-window) ;; use 'C-c q' to quit eaf apps
  (eaf-bind-key nil "C-w" eaf-browser-keybinding) ;; unbind 'C-w' for easy window switching

  ;; set default fonts for apps
  (setq eaf-webengine-font-family "JetBrainsMono Nerd Font Propo")
  (setq eaf-webengine-fixed-font-family "JetBrainsMono Nerd Font Mono")
  
  (when (display-graphic-p) ;; default for links (when in gui)
    (setq browse-url-browser-function 'eaf-open-browser-other-window)
    ;; change for rendering html mail
    (after! mu4e
      (add-to-list 'mu4e-view-actions
                   '("eaf browser" . (lambda (msg)
                                       (let ((browse-url-browser-function 'eaf-open-browser))
                                         (mu4e-action-view-in-browser msg)))) t)))
  
  (advice-remove 'find-file #'eaf--find-file-advisor)) ;; prevent auto open in eaf tool

#+end_src

** Benchmark

#+begin_src emacs-lisp
(my/report-time "Editor")

#+end_src

* Custom

#+begin_src emacs-lisp
(setq my/section-start-time (current-time))

#+end_src

** Btop Posframe

Here we create a toggleable btop instance inside a posframe. I've tried other system monitor tools more native to emacs but nothing comes close to btop. 

#+begin_src emacs-lisp
(defun my/btop-posframe-toggle ()
  "Toggle a floating btop in a posframe."
  (interactive)
  (let* ((buf-name "*btop-posframe*")
         (buf (get-buffer buf-name))
         (pframe (and buf (buffer-local-value 'posframe--frame buf))))
    (cond
     ((and pframe (frame-live-p pframe) (frame-visible-p pframe))
      (posframe-hide buf-name))
     ((and pframe (frame-live-p pframe))
      (posframe-show buf-name
                     :poshandler #'posframe-poshandler-frame-center
                     :width 130
                     :height 40
                     :border-width 5
                     :background-color "#1e2127"
                     :accept-focus t)
      (select-frame-set-input-focus pframe))
     (t
      (with-current-buffer (get-buffer-create buf-name)
        (vterm-mode)
        (evil-collection-vterm-toggle-send-escape)
        (vterm-send-string "btop\n"))
      (let ((new-frame (posframe-show buf-name
                                      :poshandler #'posframe-poshandler-frame-center
                                      :width 130
                                      :height 40
                                      :border-width 5
                                      :background-color "#1e2127"
                                      :accept-focus t)))
        (run-with-timer 0.2 nil #'select-frame-set-input-focus new-frame))))))

;; (global-set-key (kbd "C-c b") #'my/btop-posframe-toggle)
(map! :leader :desc "Toggle Btop" "os" #'my/btop-posframe-toggle)

#+end_src

** Benchmark

#+begin_src emacs-lisp
(my/report-time "Custom")

#+end_src
