* Introduction :TODO:

The follwing is my DOOM config in literate form for not only better navigation, but a better learning experience.

I spent a while trying to recreate what doom gives and all I ended up with was a worse version of doom. So this is the end game.

** Navigation

The main navigation of this file is done through the custom minor mode =config-mode= which is setup later in the Core -> Conifg section of the document. Essentially, =config-mode= will setup a sidebar with the heading levels where you can navigate and filter out only the content from that heading.

To open up the config file with =config-mode= enabled, the shortcut =<leader>C= is used. Once editing the document, there are a few options for navigating while using =config-mode=:

1. Selecting the header using the sidebar

   Switch over to the sidebar buffer and select (=RETURN=) the desired heading

2. Using =config-mode= shortcuts

   * =C-c C-n= or =C-c C-p= for next and previous headers
   * =C-c C-S-n= or =C-c C-S-p= for next and previous /section/

3. Toggle the sidebar

   You can also toggle the sidebar at any point to edit the document as a regular org file using =C-`=

Additionally, if at any point you add or remove a heading you can use the binding =U= while within the sidebar buffer to update the list.


* Core

** Nano Packages

There are a few UI based nano packages that need to be installed first. We'll declare them through the [[file:packages.el][packages.el]] file

#+begin_src emacs-lisp :tangle "packages.el"
;; these first 2 are necessary dependencies ;;

(package! nano-base-colors    ;; describes the base colors of nano theme
  :recipe (:host github
           :repo "rougier/nano-emacs"
           :files ("nano-base-colors.el")))

(package! nano-faces          ;; defines faces for nano theme
  :recipe (:host github
           :repo "rougier/nano-emacs"
           :files ("nano-faces.el")))

(package! nano-theme
  :recipe (:host github
           :repo "rougier/nano-theme"))

(package! nano-modeline
  :recipe (:host github
           :repo "rougier/nano-modeline"
           :branch "rewrite"))

(package! svg-lib
  :recipe (:host github :repo "rougier/svg-lib"))
(package! svg-tag-mode
  :recipe (:host github :repo "rougier/svg-tag-mode"))

#+end_src


** Config

The main reason I chose a literate config for this was to mitigate the pain of configuring a large single file... by using a large single file.

However, by taking advanatage of the imenu, and some packages from [[github:rougier][rougier]], we're able to create a minor mode to ease the process of editing a literate config.

Most of this is copy/pasted from [[github:rougier/dotemacs][this section]] of his literate config

*** Sidebar

First, this will require the [[github:bmag/imenu-list][imenu-list]] plugin. We'll install it from within the [[file:packages.el][packages.el]] file.

#+begin_src emacs-lisp :tangle "packages.el"
(package! imenu-list)

#+end_src

Then, we need to disable the popup rules for this sidebar window

#+begin_src emacs-lisp
(set-popup-rule! "^\\*Ilist\\*$" :side 'left :size 36 :select t :quit nil :ttl nil)

#+end_src

And create a custom nano-modeline format rule for the sidebar. I basically just copy and pasted the default format and hardcoded the file name.

#+begin_src emacs-lisp
;; (require 'nano-modeline) ;; NOTE: possibly move this elsewhere

(defcustom nano-modeline-format-config
  (cons '(nano-modeline-element-buffer-status
          nano-modeline-element-space
          "config.el"
          nano-modeline-element-space
          "(outline)")
        '(nano-modeline-element-window-status
          nano-modeline-element-space))
  "Config mode sidebar format"
  :type 'nano-modeline-type
  :group 'nano-modeline-modes)
#+end_src

#+begin_src emacs-lisp
;;; ========================== START CONFIG MODE ==========================

(require 'imenu)
(require 'imenu-list)

(defun my/org-tree-to-indirect-buffer ()
  "Create indirect buffer for current subtree and display it
in the main window instead of creating a new split."

  (let* ((origin (selected-window))
         (target (get-mru-window nil nil t)))
    (org-tree-to-indirect-buffer)
    (let ((ibuf (current-buffer)))
      ;; kill the window Org just created
      (delete-window)
      ;; show indirect buffer where the main buffer was
      (select-window target)
      (switch-to-buffer ibuf))
    (org-show-block-all)
    (setq-local my/org-blocks-hidden nil)))

(defun my/org-sidebar ()
  "Open an imenu list on the left that allow navigation."

  (interactive)
  (setq imenu-list-after-jump-hook #'my/org-tree-to-indirect-buffer
        imenu-list-position 'left
        imenu-list-size 36
        imenu-list-focus-after-activation t)

  (let ((heading (substring-no-properties (or (org-get-heading t t t t) ""))))
    (when (buffer-base-buffer)
      (switch-to-buffer (buffer-base-buffer)))
    (imenu-list-minor-mode)
    (imenu-list-stop-timer)
    (hl-line-mode)
    ;; (face-remap-add-relative 'hl-line :inherit 'nano-subtle)
    (nano-modeline nano-modeline-format-config 'header)
    ;; (setq header-line-format
    ;;       '(:eval
    ;;         (nano-modeline-render nil
    ;;                               (buffer-name imenu-list--displayed-buffer)
    ;;                               "(outline)"
    ;;                               "")))
    (setq-local cursor-type nil)
    (when (> (length heading) 0)
      (goto-char (point-min))
      (search-forward heading)
      (imenu-list-display-dwim))))

#+end_src

This toggles the org sidebar

#+begin_src emacs-lisp
(defun my/org-sidebar-toggle ()
  "Toggle the org-sidebar"

  (interactive)
  (if (get-buffer-window "*Ilist*")
      (progn
        (quit-window nil (get-buffer-window "*Ilist*"))
        (switch-to-buffer (buffer-base-buffer)))
    (my/org-sidebar)))

#+end_src

Make sure tangle is applied to the base buffer and not the subtree.

#+begin_src emacs-lisp
(defun my/org-babel-tangle ()
  "Write code blocks to source-specific files from the base buffer."

  (interactive)
  (with-current-buffer (or (buffer-base-buffer)
                           (current-buffer))
    (org-babel-tangle)))

#+end_src

Toggle code block folding; starting folded

#+begin_src emacs-lisp
(defvar my/org-blocks-hidden nil)

(defun my/org-toggle-blocks ()
  "Toggle code blocks folding."

  (interactive)
  (if my/org-blocks-hidden
      (org-show-block-all)
    (org-hide-block-all))
  (setq-local my/org-blocks-hidden (not my/org-blocks-hidden)))

(add-hook 'config-mode-hook #'my/org-toggle-blocks)

#+end_src

#+begin_src emacs-lisp
(defvar my/imenu-list-folding-status t
  "Folding status of the imenu-list")

(defun my/imenu-list-toggle-folding ()
  "Toggle top level nodes of the imenu-list buffer"

  (interactive)
  (with-current-buffer "*Ilist*"
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward "^\\+ " nil t)
        (if my/imenu-list-folding-status
            (hs-hide-block)
          (hs-show-block)))
      (setq my/imenu-list-folding-status (not my/imenu-list-folding-status)))))

(bind-key "S-<tab>" #'my/imenu-list-toggle-folding imenu-list-major-mode-map)

#+end_src

Some information for when a top node is closed

#+begin_src emacs-lisp
(defun my/display-code-line-counts (ov)
  (when (eq 'code (overlay-get ov 'hs))
    (overlay-put ov 'display
                 (propertize
                  (format " [%d sections] … "
                          (- (count-lines (overlay-start ov)
                                       (overlay-end ov)) 1))
                  'face 'nano-faded))))

(setq hs-set-up-overlay #'my/display-code-line-counts)

#+end_src

#+begin_src emacs-lisp
(defun my/imenu-list-display-dwim ()
  "Display or toggle the entry at `point'."
  (interactive)
  (save-selected-window
    (save-excursion
      (my/imenu-list-ret-dwim))))

(defun my/imenu-list-ret-dwim ()
  "Jump to or toggle the entry at `point'."
  (interactive)
  (save-excursion
    (let ((entry (imenu-list--find-entry)))
      (when (imenu--subalist-p entry)
        (setq entry (cons
                     (car entry)
                     (get-text-property 0 'marker (car entry)))))
      (imenu-list--goto-entry entry))))

(bind-key "<SPC>" #'my/imenu-list-display-dwim imenu-list-major-mode-map)
(bind-key "<return>" #'my/imenu-list-ret-dwim imenu-list-major-mode-map)

#+end_src

*** Filter :BINDING:

This provide the my/org-imenu-filter that allows us to filter thw sidebar entries using the specified expression (e.g. “+HOOK +DEFER”).

#+begin_src emacs-lisp
(bind-key "C-c f" #'my/org-imenu-filter)
(bind-key "f" #'my/org-imenu-filter imenu-list-major-mode-map)
(bind-key "U" #'imenu-list-refresh imenu-list-major-mode-map)

#+end_src

3 levels for org-imenu

#+begin_src emacs-lisp
(setq org-imenu-depth 3)

#+end_src

#+BEGIN_QUOTE
   If you end up changing the line-height (in the =UI -> Font= section)
    you'll need to change the =:height= parameter in the =svg-tags= call of
    the =my/org-imenu-filter-tree= to =1= for the tags to not look distorted
#+END_QUOTE

#+begin_src emacs-lisp
(require 'org)
(require 'svg-tag-mode)

(defvar my/org-imenu-filter-history
  '("BINDING" "HOOK" "ADVICE" "FACE" "MODE" "DEFER" "TODO"
    "PERSONAL" "INACTIVE" "BUGFIX" "OTHER" "TIMER" "OS")
  "Filter history list.")

(defvar my/org-imenu-filter-function
  (cdr (org-make-tags-matcher "*"))
  "Filter function to decide if a headline is kept")

(defun my/org-imenu-filter ()
  "Define and apply a new filter"

  (interactive)
  (let* ((match (completing-read-multiple
                 "FILTER: "
                 my/org-imenu-filter-history
                 nil nil nil
                 'my/org-imenu-filter-history))
         (match (mapconcat #'identity match " ")))
    (when (string= "" match)
      (setq match "*"))
    (setq my/org-imenu-filter-function
          (cdr (org-make-tags-matcher match)))
    (imenu-list-refresh)))


(defun my/org-imenu-filter-tree (&optional bound parent-match)
  "Build a imenu list using current filter function"

  (let* ((headlines '()))
    (save-excursion
      (org-with-wide-buffer
       (unless bound
         (setq bound (point-max))
         (goto-char (point-min)))
       (while (re-search-forward org-heading-regexp bound t)
         (let* ((element (org-element-at-point))
                (begin (org-element-property :begin element))
                (end (org-element-property :end element))
                (marker (copy-marker begin))
                (level (org-element-property :level element))
                (tags (save-excursion
                         (goto-char begin)
                          (org-get-tags)))
                (match (save-excursion
                         (goto-char begin)
                         (funcall my/org-imenu-filter-function
                                  nil (org-get-tags) level)))

                (title (org-element-property :raw-value element))
                (title (org-link-display-format
                        (substring-no-properties title)))
                (title (propertize title 'org-imenu-marker marker
                                         'org-imenu t))
                (title (if (member "INACTIVE" tags)
                           (propertize title 'face 'nano-faded)
                         title))
                (svg-tags (mapconcat #'(lambda (tag)
                                     (propertize tag 'display (svg-tag-make tag
                                                                            :face 'nano-faded
                                                                            :height 0.75)))
                                 tags " "))
                (title (if tags (format "%s %s" title svg-tags) title))
                (title (propertize title 'marker marker))
                (children (my/org-imenu-filter-tree end match)))
           (goto-char end)

           (cond ((> level org-imenu-depth)
                  nil)
                 ((> (length children) 0)
                  (add-to-list 'headlines (append (list title) children) t))
                 ((or match parent-match)
                  (add-to-list 'headlines (cons title marker) t)))))))
    headlines))

(advice-add #'org-imenu-get-tree :override #'my/org-imenu-filter-tree)

#+end_src


*** Config mode

This section defines the =my/config-mode= to ease navigating and editing the configuration file.

Navigation commands using the ilist menu.

#+begin_src emacs-lisp
(defun my/config-mode-prev-header ()
  "Move to previous header"

  (interactive)
  (with-current-buffer "*Ilist*"
    (search-backward-regexp "^  ")
    (imenu-list-display-dwim)))

(defun my/config-mode-next-header ()
  "Move to next header"

  (interactive)
  (with-current-buffer "*Ilist*"
    (forward-line)
    (search-forward-regexp "^  ")
    (imenu-list-display-dwim)))

(defun my/config-mode-prev-section ()
  "Move to previous section"

  (interactive)
  (with-current-buffer "*Ilist*"
    (search-backward-regexp "\\+ " nil nil 2)
    (forward-line)
    (imenu-list-display-dwim)))

(defun my/config-mode-next-section ()
  "Move to next section"

  (interactive)
  (with-current-buffer "*Ilist*"
    (previous-line)
    (search-forward-regexp "\\+ ")
    (forward-line)
    (imenu-list-display-dwim)))

#+end_src

The minor mode for configuration

#+begin_src emacs-lisp
(define-minor-mode my/config-mode
  "Configuration mode"

  :init-value nil
  :global nil
  :keymap (let* ((map (make-sparse-keymap)))
            (bind-key "C-c C-p"   #'my/config-mode-prev-header map)
            (bind-key "C-c C-n"   #'my/config-mode-next-header map)
            (bind-key "C-c C-S-p" #'my/config-mode-prev-section map)
            (bind-key "C-c C-S-n" #'my/config-mode-next-section map)
            (bind-key "C-`"       #'my/org-sidebar-toggle map)
            ;; (bind-key "C-c C-v t" #'my/org-babel-tangle map)   ;; We dont need these
            ;; (bind-key "C-c t"     #'my/org-toggle-blocks map)
            map)

  (require 'org)
  (if my/config-mode
      (my/org-sidebar)))

#+end_src

And lastly, define a shortcut function to open this file with config mode enabled. We will also bind this to a key for easy access. I chose =<leader>C=

#+begin_src emacs-lisp
(defun my/config ()
  "Open Doom config in the current frame with config-mode enabled."

  (interactive)
  (find-file "~/.config/doom/config.org")
  (my/config-mode 1))

(map! :leader
      :desc "Open Doom config (config-mode)"
      "C" #'my/config)

;;; =========================== END CONFIG MODE ===========================
#+end_src


** Terminal :TODO:

Within *Nexus*, terminal usage is just as important as the GUI.

Doom handles most of this for us but there's some aspects we still need to change.

First, we enable mouse usage in the terminal

#+begin_src emacs-lisp
(unless (display-graphic-p)
  (xterm-mouse-mode 1)
  (global-set-key (kbd "<mouse-4>") 'scroll-down-line)
  (global-set-key (kbd "<mouse-5>") 'scroll-up-line))

#+end_src

* UI

Much of the UI tweaks are inspired by [[github:rougier/nano-emacs][nano emacs]]. Simple, although not to the extreme of nano, and cohesive layouts with minimal color pallettes.

** Font :TODO:

The default font settings for the nano theme assume the Roboto font, which I personally don't care for. We can change those here.

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "JetBrainsMono Nerd Font" :size 16))

;; (setq nano-mono)

#+end_src

Then increasing the default line height.

#+begin_src emacs-lisp
(setq-default line-spacing 6)
;; (add-hook 'org-mode-hook (lambda () (setq-default line-spacing 6)))
;; (add-hook 'org-mode-hook (lambda () (setq-default line-spacing 6)))
;; (add-hook 'org-mode-hook (lambda () (setq-default line-spacing 6)))

#+end_src

** Theme :TODO:

Here we can set the base nano theme

#+begin_src emacs-lisp
(setq doom-theme 'doom-tokyo-night)
;; (load-theme 'nano-dark t)

#+end_src

Then, we can source the outside file =<file name>= which is responsible for manipulating the face colors.

This file, generated by matugen, will maniputlate the main and accent color of nano-dark to match the current matugen theme.

#+begin_quote
   If you do not use =matugen= or simply want to use a different theme
    then you can comment this out
#+end_quote

#+begin_src emacs-lisp

#+end_src
** Layout :TODO:

Nano offers a different perspective when it comes to editor layouts. It provides more spacing/gaps between windows and creates a layout that feels comfortable and easier to intake visually.

We capitalize on this by using some of the Nano defaults

First, we increase the padding on frames

#+begin_src emacs-lisp
(setq default-frame-alist
      (append (list
               '(min-height . 1)
               '(height     . 45)
               '(min-width  . 1)
               '(width      . 81)
               '(vertical-scroll-bars . nil)
               '(internal-border-width . 20)
               '(left-fringe    . 8)
               '(right-fringe   . 8)
               '(tool-bar-lines . 0)
               '(menu-bar-lines . 0))))

#+end_src

Then we increase the gap between windows

#+begin_src emacs-lisp
(setq window-divider-default-right-width 24)
#+end_src

We also need to change the face value for the gap between windows. However, we need to do this after the theme's set, so we'll need to add a hook function. This will have to happen after the solaire package is activated since it alters face colors.

#+begin_src emacs-lisp
(add-hook 'solaire-mode-hook
          (lambda ()
            (let ((bg (face-background 'default)))
              (dolist (face '(window-divider
                              window-divider-first-pixel
                              window-divider-last-pixel
                              vertical-border))
                (set-face-attribute face nil
                  :foreground bg
                  :background bg
                  :distant-foreground bg
                  :inherit nil))
              (redraw-display))))

#+end_src


** Line Numbers :MODE:

I use relative line numbers throughout the editor for easier vim navigation. We can apply this globally using the =global-display-line-numbers-mode= and then conditionally remove them for certain buffers (like org mode)

#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode)

#+end_src


** Modeline :TDOD:HOOK:

The modeline in nano is something that really bought me. Its extemely simple and isn't even a modeline really; Its a headerline with interactive buttons and features depending on the mode you're in.

It also has a nice API for creating new formats, or editing existing ones (althought not documented at all). To take advantage of this we use the =rewrite= branch of the config, as the master branch is far behind this one.

First, we'll add a hook to load nano-modeline. This will have to happen after the theme has been loaded for the faces to be represented accurately. Then we need to conceal the default modeline for every buffer.

#+begin_src emacs-lisp
(add-hook 'doom-load-theme-hook (lambda () (require 'nano-modeline)))
(add-hook 'after-change-major-mode-hook (lambda () (hide-mode-line-mode 1)))

#+end_src

We can then define some hooks for enabling the modeline

#+begin_src emacs-lisp
(add-hook! org-mode #'nano-modeline)
(add-hook! prog-mode #'nano-modeline)
(add-hook! text-mode #'nano-modeline)
(add-hook! messages-buffer-mode #'nano-modeline)
(add-hook 'vterm-mode-hook (lambda ()              ;; special modes require their format
                             (nano-modeline
                              nano-modeline-format-terminal 'header)))

#+end_src

* Editor

** Dired Replacement :BINDING:

We replace dired with [[github:alexluigit/dirvish][dirvish]] as it comes with better defaults and better UI. So we install this using the =package!= macro within the [[file:packages.el][packages.el]] file

#+begin_src emacs-lisp :tangle "packages.el"
(package! dirvish)

#+end_src

Then we can configure it within [[file:config.el][config.el]]

#+begin_src emacs-lisp
(use-package! dirvish
  :hook
  (emacs-startup . dirvish-override-dired-mode)        ;; override dired
  (dired-mode . (lambda () (display-line-numbers-mode 0)))  ;; no numbers

  :custom
  (dirvish-quick-access-entries
   '(("d" "~/Downloads/"                "Downloads")
     ("p" "~/Projects"                  "Projects")
     ("c" "~/.config"                   "Configs")
     ("i" "~/Pictures"                  "Pictures")
     ("s" "~/scripts"                   "Scripts")
     ("m" "/mnt/"                       "Drives")
     ("e" "/sudo:root@localhost:/etc"   "Modify program settings")))

  :config
  ;; core modes
  (dirvish-peek-mode)
  (dirvish-side-follow-mode)

  ;; use 'exa' for previews
  (dirvish-define-preview eza (file)
    "Use `eza' to generate directory preview."
    :require ("eza")
    (when (file-directory-p file)
      `(shell . ("eza" "--color=always" "--icons=always"
                 "--group-directories-first" ,file))))
  (push 'eza dirvish-preview-dispatchers))

#+end_src

Then we can override dired by replacing its default mapping

#+begin_src emacs-lisp
(map! :leader
      :desc "Open Dirvish"
      "o-" #'dirvish)

#+end_src

** Org Tweaks

*** Remove Line Numbers :HOOK:

I personally don't use line numbers when editing org documents, so we can remove those here

#+begin_src emacs-lisp
(add-hook 'org-mode-hook (lambda () (global-display-line-numbers-mode 0)))

#+end_src


** Vterm Tweaks :HOOK:

Here we make some configuration tweaks to vterm windows and its behavior.

We'll start by editing the window UI. First, we'll disable line numbers for the vterm buffer and revert the default line-spacing to 1.

#+begin_src emacs-lisp
(add-hook 'vterm-mode-hook (lambda ()
                             (display-line-numbers-mode 0)
                             (setq-local line-spacing 1)))

#+end_src

Next we'll focus on the behavior of vterm

#+BEGIN_QUOTE
   If you use a different shell (like zsh) you'll need to replace that here
#+END_QUOTE

#+begin_src emacs-lisp
(setq vterm-shell "/bin/nu")

#+end_src

And then we'll set some QoL keybindings. First up, toggling the vterm popup.

Since vterm won't allow us to have a single global keybinding, we'll have to bind it to a =C-c= prefix when within a vterm buffer

#+begin_src emacs-lisp
;; unmap C-e and use as global toggle
(after! evil
  (map! :m "C-e" nil)
  (map! :g "C-e" #'+vterm/toggle))

;; add toggle from within vterm
(after! vterm
  (add-to-list 'vterm-keymap-exceptions "C-e")
  (map! :map vterm-mode-map "C-c o" #'+vterm/toggle))

#+end_src

Then, we can define some keymaps for working within the terminal

#+begin_src emacs-lisp
(after! vterm
  ;; switching workspaces
  (map! :map vterm-mode-map "C-c ," #'+workspace/switch-right)
  (map! :map vterm-mode-map "C-c ." #'+workspace/switch-left))

#+end_src

** Languages/LSP

*** Hyprlang :HOOK:

Hyprland's config language isn't outright supported by most packages, so we'll have to manually add all of the behavior.

We'll start by installing =hyprlang-ts-mode= using [[file:packages.el][packages.el]]

#+begin_src emacs-lisp :tangle "packages.el"
(package! hyprlang-ts-mode)

#+end_src

Then configuring it to activate on hypr files, and adding it to our tree-sitter source list

#+begin_src emacs-lisp
(defun my-hyprlang-detect ()
  "Activate hyprlang-ts-mode for any .conf file in a hypr/ directory."
  (when (and buffer-file-name
             (string-match-p "/hypr/.*\\.conf\\'" buffer-file-name))
    (require 'hyprlang-ts-mode)
    (hyprlang-ts-mode)))

(add-hook 'find-file-hook #'my-hyprlang-detect)

(add-to-list 'treesit-language-source-alist
             '(hyprlang "https://github.com/tree-sitter-grammars/tree-sitter-hyprlang"))

#+end_src

#+BEGIN_QUOTE
   You may need to manually install the grammar before using it
    =M-x treesit-install-language-grammar= -> =hyprlang=
#+END_QUOTE

To use the community LSP for hyprland config files, hyprls, we have to add it to our LSP config

#+BEGIN_QUOTE
   If you do not have the [[github:hyprland-community/hyprls][hyprls]] package, youll need to install it
#+END_QUOTE

#+begin_src emacs-lisp
(after! lsp-mode
  (add-to-list 'lsp-language-id-configuration '(hyprlang-ts-mode . "hyprlang"))
  (lsp-register-client
   (make-lsp-client
    :new-connection (lsp-stdio-connection '("hyprls"))
    :activation-fn (lsp-activate-on "hyprlang")
    :server-id 'hyprls)))

(add-hook 'hyprlang-ts-mode-hook #'lsp-deferred)

#+end_src
